# Generated by Django 3.2.4 on 2021-07-04 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alter_app', '0004_rename_aws_location_art_psd_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='psd_filename',
        ),
        migrations.AddField(
            model_name='art',
            name='file',
            field=models.FileField(default=None, upload_to='psd/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='art',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to='thumb/'),
        ),
    ]
